package edu.umn.msse.busbuddy.alert.domain.model;

import java.io.Serializable;
import java.util.Date;

import edu.umn.msse.busbuddy.alert.client.model.UserInformation;
import edu.umn.msse.busbuddy.alert.domain.AlertFactory;
import edu.umn.msse.busbuddy.alert.domain.AlertRepository;
import edu.umn.msse.busbuddy.alert.enums.AlertInitiator;
import edu.umn.msse.busbuddy.alert.enums.AlertNotificationType;
import edu.umn.msse.busbuddy.alert.enums.AlertRunType;
import edu.umn.msse.busbuddy.alert.enums.AlertStatus;

/**
 * This is a base Alert Model that has most of the common information about an Alert. {@link OneTimeAlert} and
 * {@link RecurringAlert} extends this Alert Model. Alert can only be created from {@link alert.domain.AlertFactory} and then
 * manipulated from {@link alert.domain.AlertRepository}.
 */
public class Alert implements Serializable {

	private static final long serialVersionUID = -5671884600600864426L;

	/**
	 * A unique identifier for Alert.
	 */
	private String alertGuid;

	/**
	 * A text description about the alert that the user or other modules want to remember.
	 */
	private String description;

	/**
	 * DateTime that the alert was created.
	 */
	private Date createdDateTime;

	/**
	 * DateTime that the alert should start running.
	 */
	private Date startDateTime;

	/**
	 * DateTime that the alert would expire.
	 */
	private Date expireDateTime;

	/**
	 * current status of the alert. The value depends upon {@link alert.enums.AlertStatus} enum.
	 */
	private AlertStatus Status;

	/**
	 * Count of error occurrence when the alert was ran.
	 */
	private int errorCount;

	/**
	 * Notification type of alert. Depends upon the value as specified in {@link alert.enums.AlertNotificationType}
	 */
	private AlertNotificationType alertType;

	/**
	 * Run type of alert e.g., one time or recurring. Value is defined by {@link alert.enums.AlertRunType}
	 */
	private AlertRunType alertRunType;

	/**
	 * Module that initiated or created this alert. {@link alert.enums.AlertInitiator}
	 */
	private AlertInitiator alertInitiator;

	/**
	 * Information about the user if the alert is created by a dedicated user. For any alerts generated by Transit or
	 * Tracking module, the user can either be admin of that module or the admin of the bus service provider.
	 * {@link alert.client.model.UserInformation}
	 */
	private UserInformation userInformation;

	/**
	 * A HashMap of
	 */
	private TripInformation tripInformation;

	public String getAlertGuid() {
		return alertGuid;
	}

	public void setAlertGuid(String alertGuid) {
		this.alertGuid = alertGuid;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedDateTime() {
		return createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	public Date getStartDateTime() {
		return startDateTime;
	}

	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}

	public Date getExpireDateTime() {
		return expireDateTime;
	}

	public void setExpireDateTime(Date expireDateTime) {
		this.expireDateTime = expireDateTime;
	}

	public AlertStatus getStatus() {
		return Status;
	}

	public void setStatus(AlertStatus status) {
		Status = status;
	}

	public int getErrorCount() {
		return errorCount;
	}

	public void setErrorCount(int errorCount) {
		this.errorCount = errorCount;
	}

	public AlertNotificationType getAlertType() {
		return alertType;
	}

	public void setAlertType(AlertNotificationType alertType) {
		this.alertType = alertType;
	}

	public AlertRunType getAlertRunType() {
		return alertRunType;
	}

	public void setAlertRunType(AlertRunType alertRunType) {
		this.alertRunType = alertRunType;
	}

	public UserInformation getUserInformation() {
		return userInformation;
	}

	public void setUserInformation(UserInformation userInformation) {
		this.userInformation = userInformation;
	}

	public TripInformation getTripInformation() {
		return tripInformation;
	}

	public void setTripInformation(TripInformation tripInformation) {
		this.tripInformation = tripInformation;
	}

	public AlertInitiator getAlertInitiator() {
		return alertInitiator;
	}

	public void setAlertInitiator(AlertInitiator alertInitiator) {
		this.alertInitiator = alertInitiator;
	}

}
